general:
  steps:
    fetch_fcst_data: true
    fetch_obs_data: true
    pair_data: true
    compute_metrics: true
    plot_metrics: true
  location_set_name: usgs_01123000
  location_list: ['01123000']
  location_type: usgs_gage
  location_group_size: 500
  variable_name: streamflow
  nwm_configuration: long_range_mem4
  dataset_name: [noah_cfes]
  nwm_version: [ngen]
  forecast_start_date: ['2022-12-01 00:00:00']
  forecast_end_date: ['2022-12-01 00:00:00']
file_paths:
  base_dir: /home/yuqiong.liu/repos/nwm-verf/data
  location_list_file: '{base_dir}/inputs/gage_files/usgs_gages_link_CONUS_calib100.csv'
  crosswalk_file: '{base_dir}/inputs/gage_files/usgs_{nwm_version}_crosswalk_all_domains.parquet'
  gage_hydrofabric_file: '{base_dir}/inputs/gage_files/gage_hydrofabric_all_domains.parquet'
  fcst_config_file: '{base_dir}/inputs/nwm_forecast_configuration.yaml'
  fcst_data_file: '{base_dir}/inputs/{location_set_name}/{dataset_name}/{nwm_configuration}.csv'
  output_dir: '{base_dir}/outputs/{location_set_name}'
nwm_forecast:
  fetch_fcst: [true]
  output_type: channel_rt
  t_minus: [0, 1, 2]
  data_source: ngenCERF
  kerchunk_method: local
  process_by_z_hour: true
  stepsize: 100
  ignore_missing_file: false
  overwrite_output: false
  memory_per_worker_gb: 3
flow_observation:
  usgs:
    chunk_by: month
    overwrite_output: true
    memory_per_worker_gb: 3
pair_data:
  overwrite: true
  group_size: 200
metrics:
  overwrite: true
  library: nwm.eval
  metric_subset: all
  flow_threshold_categorical: 0.9
  flow_threshold_event: 0.9
  lead_times: [all_aggregated]
  file_format: parquet
plots:
  time_series:
    plot: true
    metric_subset: []
    lead_times: []
  metric_table:
    plot: true
    metric_subset: []
    lead_times: []
  barchart:
    plot: true
    metric_subset: []
    lead_times: []
